QT = core
CONFIG += c++14 console
CONFIG -= app_bundle
lessThan(QT_MAJOR_VERSION, 5): QMAKE_CXXFLAGS += -std=c++14
DEFINES += \
  QT_DEPRECATED_WARNINGS \
  QT_DISABLE_DEPRECATED_BEFORE=0x060000 \
  QT_RESTRICTED_CAST_FROM_ASCII \
  QT_NO_FOREACH
SOURCES = main.cpp
