#ifndef SYSCALL_KERNEL_H
#define SYSCALL_KERNEL_H
// This file is automatically generated from syscalls.py

void _k_putch(char _n, char ch); // #1
char _k_getch(char _n); // #3

#endif // SYSCALL_KERNEL_H
