#ifndef SYSCALL_USER_H
#define SYSCALL_USER_H
// This file is automatically generated from syscalls.py

extern void _k_putch(char _n, char ch); // #1
extern char _k_getch(char _n); // #3

#define putch(ch) (_k_putch(1, (ch)))
#define getch() (_k_getch(3))

#endif // SYSCALL_USER_H
