; This file is automatically generated from syscalls.py

; Dispatch Table
syscall_table:
	.dw	_k_putch          ; #1
	.dw	_k_not_impl_      ; #2
	.dw	_k_getch          ; #3

; Dispatcher
_k_not_impl_:
_k_putch:
_k_getch:
	;
	
	add iy, sp
	ld  e, (iy) ; _n
	cp
